console.log("Hello world!!!!")
console.log("Mangesh is time traveller")
console.log("Kalam is on festival mood, yeahhhhhhh")
console.log("Sapphire starsssssssssssss")
console.log("CEO:Pranita")
console.log("Kalam is on festival mood")
console.log("Sapphire stars")
console.log("yessssssssssssssssss")
console.log("helooooooooooooooooooo")
console.log("CEO")
console.log("Vadapav")
console.log("Heroku")
console.log("Something")
